title: Default
fields:
  title:
    label: Title
    type: text
  description:
    label: Meta Description
    type: text
  subtitle:
    label: Subtitle
    type: text
  blocks:
    type: blocks
    fieldsets:
      - heading
      - text
      - image
      - listing
      - list         

