
columns:
  - width: 1/2
    sections:
      pages:
        type: pages
        templates:
          - start
          - default
          - error
          - about 
          - now
          - colophon
          - today

  - width: 1/2
    sections:
      projects: sections/projects
      wallpapers: sections/wallpapers



       
